name: "Security Vulnerability Report"
description: "Report a security vulnerability affecting the NeoPod website (NEO Ambassador Website)."
title: "[Security] <Short Description>"
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: overview
    attributes:
      label: "Security Issue Overview"
      description: "Describe the security vulnerability and how it impacts the application."
      placeholder: "Two security vulnerabilities were identified in the React Server Components (RSC) protocol that impact Next.js applications using the App Router..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Impact"
      description: "Explain the potential impact and severity of this vulnerability."
      placeholder: "Potential denial-of-service, source code exposure, data leakage, etc."
    validations:
      required: true

  - type: textarea
    id: affected_components
    attributes:
      label: "Affected Components"
      description: "List the affected pages, APIs, features, or dependencies."
      placeholder: "Next.js App Router, React Server Components, Server Actions..."
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce (if applicable)"
      description: "Provide steps or conditions to reproduce the issue, if known."
      placeholder: "1. Send a crafted request to...\n2. Observe server behavior..."
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: "Mitigation / Resolution"
      description: "Describe how the issue can be mitigated or how it was resolved."
      placeholder: "Upgraded Next.js and React to patched versions..."
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "References (CVE, advisories, links)"
      description: "Include any related CVEs, advisories, or external references."
      placeholder: "CVE-2025-55183, CVE-2025-67779"
    validations:
      required: false
